export interface CarrierUpload
{
    MC: string,
    NAME: string,
    CITY: string,
    STATE: string,
    COUNTRY: string,
    PHONE: string,
    CONTACT: string,
    LPMEMAIL: string,
    TAXID: string,
    QUICKPAYDISCOUNT: number,
    DOT: string,
    LASTDOTUPDATE: string,
    FACTORINGCOMPANYID: number,
    FACTORINGEMAIL: string,
    EQUIPMENTTYPEID: number,
    VANSNUMB: number,
    REEFERSNUMB: number,
    FLATBEDS: number,
    STEPDECKS: number,
    STATUSID: number,
    NOTES: string,
    STREET: string,
    HOUSENUMBER: string,
    ZIPCODE: string,
    ADRESS: string,
    INSURANCEEXPDATE: string,
    EQUIPMENTTYPEDES: string,
    FACTORINGCOMPANYDES: string,
}

export interface TrailerUpload
{
    TRAILERNUMBER: string,
    MAKE: string,
    OWNER: string,
    TYEAR: number,
    IDNUMBER: string,
    LICENSEPLATE: string,
    LICENSEEXPDATE: string,////DATE
    ANNUALINSPECTION: string,///DATE
    PHYSICALDAMAGE: boolean,
    ROOFTYPE: number,
    WEIGHT: number,
    UNITCODE: string,
    VENTILATION: boolean,
    AIR: boolean,
    WHEELREPOSITION: boolean,
    NOTES: string,
    STATUSID: number,
    TRAILERTYPE: string,
    ROOFTYPEDES: string,
    TRAILEREDES: string,
    URLS: string,
}
